### ISSUE TITLE
请问这个怎么运行？

### ISSUE THREAD

**Issue by Smith-yukino** [birdx-007/Kita-Flower#2]
大佬你好，请问这个下载后怎么运行

**Comment by birdx-007** [comment]
需要在Qt5环境下构建这个项目！
不过考虑到便利性，我刚刚发布了一个含可执行文件的Release，可以到Code页面查看^^

**Comment by Smith-yukino** [comment]
好的，谢谢
我马上去尝试

**Comment by Smith-yukino** [comment]
我只在Beta版本中找到了运行程序，没有在Code里看到可执行的文件Release  请问这个需要什么依赖环境呢

**Comment by Smith-yukino** [comment]
我在Release中找到了Kita.ext ,双击运行却发生了系统错误
![内网通截图20230222171435](https://user-images.githubusercontent.com/112156890/220575074-f63eb597-5234-48de-9978-9cda721756b2.png)

**Comment by birdx-007** [comment]
![image](https://user-images.githubusercontent.com/79506351/220584330-1f101649-33c4-4c45-b9c8-cfdf010704eb.png)
这个问题是由于你的电脑没有gcc相关的依赖（图上显示的这几个dll）
你可以去网上搜索一下这三个dll把它们下载到exe的同一个目录里，应该就没问题了^^
我稍后也会更新beta版本里的相关文件>^

**Comment by birdx-007** [comment]
相关文件已更新^^

**Comment by Smith-yukino** [comment]
^_^,我已经完美运行

**Comment by Smith-yukino** [comment]
thanks
